### ISSUE TITLE
SouthWest website redirects and no selectors in the code can be found after querying

### ISSUE THREAD

**Issue by jimdsouza** [ezekg/swa-dashboard#36]
`(get) loaded [get] https://www.southwest.com/  

(submit) loaded [post] https://www.southwest.com/flight/search-flight.html?int=HOMEQBOMAIR {"returnAirport":"RoundTrip","twoWayTrip.x":0,"twoWayTrip.y":0,"twoWayTrip":true,"fareType.x":0,"fareType.y":0,"fareType":"DOLLARS","submitButton":"true","airTranRedirect":"","outboundTimeOfDay":"ANYTIME","returnTimeOfDay":"ANYTIME","seniorPassengerCount":0,"originAirport":"LAX","destinationAirport":"JFK","outboundDateString":"11/11/2017","returnDateString":"12/12/2017","adultPassengerCount":1} 

(find) no results for "#faresOutbound .product_price, #b0Table span.var.h5" `

These are the osmosis.log and osmosis.error outputs

**Comment by ezekg** [comment]
It doesn't look like Southwest has flights to JFK:

![image](https://cloud.githubusercontent.com/assets/6979737/22892994/0c6e88f2-f1da-11e6-9c69-0c2f4ac4306b.png)

This script could use some validation for flights that don't exist. If you would like to make a PR, I can get that merged in. This issue is a dup of #16, #7 and #4, so I'm going to close it.
